baseURL = 'https://nicoloboschi.com/'
languageCode = 'en-us'
title = 'Some tech stuff'
theme = 'hugo-bearcub'
copyright = "Nicolò Boschi"

enableRobotsTXT = true
pagination.pagerSize = 10

[permalinks]
posts = "/posts/:year:month:day"

[markup]
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = false
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
description = "Software Engineer. Distributed Systems. AI Agents. Open Source."
favicon = "favicon.jpg"
dateFormat = "2006-01-02"
themeStyle = "original"
madeWith = ""
images = ["cover.jpg"]
generateSocialCard = true

[params.author]
email = "boschi1997@gmail.com"
name = "Nicolò Boschi"

